# Hardpoint: build and system installation.
#
# The game generates every asset at runtime, so an install is the two binaries,
# an icon, a desktop entry, a service unit and the manuals. Nothing else.

PREFIX      ?= /usr/local
DESTDIR     ?=
CARGO       ?= cargo
BINDIR       = $(DESTDIR)$(PREFIX)/bin
DATADIR      = $(DESTDIR)$(PREFIX)/share
ICONDIR      = $(DATADIR)/icons/hicolor
APPDIR       = $(DATADIR)/applications
DOCDIR       = $(DATADIR)/doc/hardpoint
MANDIR       = $(DATADIR)/man/man6
UNITDIR     ?= $(DESTDIR)$(PREFIX)/lib/systemd/system
CONFDIR      = $(DESTDIR)/etc/hardpoint

ICON_SIZES   = 16 32 48 64 128 256
TARGET       = target/release
INSTALL      = install

.PHONY: all build icons install uninstall check clean help

all: build

help:
	@echo "make build      compile the release binaries"
	@echo "make check      run the map, traversal and match self-tests"
	@echo "make install    install to PREFIX (default /usr/local)"
	@echo "make uninstall  remove an installation from PREFIX"
	@echo
	@echo "  PREFIX=$(PREFIX)   DESTDIR=$(DESTDIR)"

build:
	$(CARGO) build --release --locked

# The icon is generated by the game itself; the repository holds no binaries.
icons: build
	@mkdir -p build/icons
	@for s in $(ICON_SIZES); do \
	  $(TARGET)/hardpoint --icon build/icons/hardpoint-$$s.png $$s >/dev/null; \
	done

# Everything the game needs to run is inside the binary, so this is enough for
# `hardpoint` to work for any user on the system.
install: build icons
	$(INSTALL) -Dm755 $(TARGET)/hardpoint        $(BINDIR)/hardpoint
	$(INSTALL) -Dm755 $(TARGET)/hardpoint-server $(BINDIR)/hardpoint-server
	@for s in $(ICON_SIZES); do \
	  $(INSTALL) -Dm644 build/icons/hardpoint-$$s.png \
	    $(ICONDIR)/$${s}x$${s}/apps/hardpoint.png; \
	done
	$(INSTALL) -Dm644 packaging/hardpoint.desktop $(APPDIR)/hardpoint.desktop
	$(INSTALL) -Dm644 README.md                   $(DOCDIR)/README.md
	$(INSTALL) -Dm644 packaging/hardpoint.6       $(MANDIR)/hardpoint.6
	$(INSTALL) -Dm644 packaging/hardpoint-server.6 $(MANDIR)/hardpoint-server.6
	$(INSTALL) -Dm644 packaging/hardpoint-server.service $(UNITDIR)/hardpoint-server.service
	$(INSTALL) -Dm644 packaging/server.conf       $(CONFDIR)/server.conf
	@echo
	@echo "Installed to $(PREFIX)."
	@echo "  hardpoint                 play"
	@echo "  hardpoint-server --help   run a dedicated server"
	@echo "  systemctl enable --now hardpoint-server   run one at boot"
	@if [ -z "$(DESTDIR)" ] && command -v gtk-update-icon-cache >/dev/null 2>&1; then \
	  gtk-update-icon-cache -q -t -f $(ICONDIR) 2>/dev/null || true; \
	fi
	@if [ -z "$(DESTDIR)" ] && command -v update-desktop-database >/dev/null 2>&1; then \
	  update-desktop-database -q $(APPDIR) 2>/dev/null || true; \
	fi

uninstall:
	rm -f $(BINDIR)/hardpoint $(BINDIR)/hardpoint-server
	@for s in $(ICON_SIZES); do \
	  rm -f $(ICONDIR)/$${s}x$${s}/apps/hardpoint.png; \
	done
	rm -f $(APPDIR)/hardpoint.desktop
	rm -f $(MANDIR)/hardpoint.6 $(MANDIR)/hardpoint-server.6
	rm -f $(UNITDIR)/hardpoint-server.service
	rm -rf $(DOCDIR)
	@echo "Removed."
	@echo "  Kept /etc/hardpoint/server.conf and per-user settings in"
	@echo "  ~/.local/share/hardpoint; delete those by hand if you want them gone."

# The self-tests that matter: every map valid, every route walkable, every
# mode played through by bots.
check: build
	$(TARGET)/hardpoint --audit
	$(TARGET)/hardpoint --stairs ALL
	$(TARGET)/hardpoint --botmatch IRONVEIL TDM 60 11 2
	$(TARGET)/hardpoint --botmatch DRYDOCK DOM 60 11 2
	$(TARGET)/hardpoint --botmatch BELVOIR "S&D" 90 11 2

clean:
	$(CARGO) clean
	rm -rf build
